package hibernateMapping;
// Generated 2016-11-7 15:03:58 by Hibernate Tools 5.2.0.Beta1

/**
 * Friend generated by hbm2java
 */
public class Friend implements java.io.Serializable {

	private Integer friendId;
	private CsdnUrl csdnUrl;
	private User user;
	private WeiboUrl weiboUrl;
	private ZhihuUrl zhihuUrl;
	private String friendName;
	private boolean hasCsdn;
	private boolean hasWeibo;
	private boolean hasZhihu;

	public Friend() {
	}

	public Friend(User user, String friendName, boolean hasCsdn, boolean hasWeibo, boolean hasZhihu) {
		this.user = user;
		this.friendName = friendName;
		this.hasCsdn = hasCsdn;
		this.hasWeibo = hasWeibo;
		this.hasZhihu = hasZhihu;
	}

	public Friend(CsdnUrl csdnUrl, User user, WeiboUrl weiboUrl, ZhihuUrl zhihuUrl, String friendName, boolean hasCsdn,
			boolean hasWeibo, boolean hasZhihu) {
		this.csdnUrl = csdnUrl;
		this.user = user;
		this.weiboUrl = weiboUrl;
		this.zhihuUrl = zhihuUrl;
		this.friendName = friendName;
		this.hasCsdn = hasCsdn;
		this.hasWeibo = hasWeibo;
		this.hasZhihu = hasZhihu;
	}

	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	public CsdnUrl getCsdnUrl() {
		return this.csdnUrl;
	}

	public void setCsdnUrl(CsdnUrl csdnUrl) {
		this.csdnUrl = csdnUrl;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public WeiboUrl getWeiboUrl() {
		return this.weiboUrl;
	}

	public void setWeiboUrl(WeiboUrl weiboUrl) {
		this.weiboUrl = weiboUrl;
	}

	public ZhihuUrl getZhihuUrl() {
		return this.zhihuUrl;
	}

	public void setZhihuUrl(ZhihuUrl zhihuUrl) {
		this.zhihuUrl = zhihuUrl;
	}

	public String getFriendName() {
		return this.friendName;
	}

	public void setFriendName(String friendName) {
		this.friendName = friendName;
	}

	public boolean isHasCsdn() {
		return this.hasCsdn;
	}

	public void setHasCsdn(boolean hasCsdn) {
		this.hasCsdn = hasCsdn;
	}

	public boolean isHasWeibo() {
		return this.hasWeibo;
	}

	public void setHasWeibo(boolean hasWeibo) {
		this.hasWeibo = hasWeibo;
	}

	public boolean isHasZhihu() {
		return this.hasZhihu;
	}

	public void setHasZhihu(boolean hasZhihu) {
		this.hasZhihu = hasZhihu;
	}

}
