package hibernateMapping;
// Generated 2016-11-5 19:39:13 by Hibernate Tools 5.2.0.Beta1

/**
 * Friend generated by hbm2java
 */
public class Friend implements java.io.Serializable {

	private Integer friendId;
	private CsdnUrl csdnUrl;
	private User user;
	private WeiboUrl weiboUrl;
	private ZhihuUrl zhihuUrl;
	private String friendName;
	private Boolean hasCsdn;
	private Boolean hasWeibo;
	private Boolean hasZhihu;

	public Friend() {
	}

	public Friend(User user, String friendName) {
		this.user = user;
		this.friendName = friendName;
	}

	public Friend(CsdnUrl csdnUrl, User user, WeiboUrl weiboUrl, ZhihuUrl zhihuUrl, String friendName, Boolean hasCsdn,
			Boolean hasWeibo, Boolean hasZhihu) {
		this.csdnUrl = csdnUrl;
		this.user = user;
		this.weiboUrl = weiboUrl;
		this.zhihuUrl = zhihuUrl;
		this.friendName = friendName;
		this.hasCsdn = hasCsdn;
		this.hasWeibo = hasWeibo;
		this.hasZhihu = hasZhihu;
	}

	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	public CsdnUrl getCsdnUrl() {
		return this.csdnUrl;
	}

	public void setCsdnUrl(CsdnUrl csdnUrl) {
		this.csdnUrl = csdnUrl;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public WeiboUrl getWeiboUrl() {
		return this.weiboUrl;
	}

	public void setWeiboUrl(WeiboUrl weiboUrl) {
		this.weiboUrl = weiboUrl;
	}

	public ZhihuUrl getZhihuUrl() {
		return this.zhihuUrl;
	}

	public void setZhihuUrl(ZhihuUrl zhihuUrl) {
		this.zhihuUrl = zhihuUrl;
	}

	public String getFriendName() {
		return this.friendName;
	}

	public void setFriendName(String friendName) {
		this.friendName = friendName;
	}

	public Boolean getHasCsdn() {
		return this.hasCsdn;
	}

	public void setHasCsdn(Boolean hasCsdn) {
		this.hasCsdn = hasCsdn;
	}

	public Boolean getHasWeibo() {
		return this.hasWeibo;
	}

	public void setHasWeibo(Boolean hasWeibo) {
		this.hasWeibo = hasWeibo;
	}

	public Boolean getHasZhihu() {
		return this.hasZhihu;
	}

	public void setHasZhihu(Boolean hasZhihu) {
		this.hasZhihu = hasZhihu;
	}

}
