package hibernateMapping;
// Generated 2016-11-10 23:45:35 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * WeiboEntry generated by hbm2java
 */
public class WeiboEntry implements java.io.Serializable {

	private Integer entryId;
	private WeiboUrl weiboUrl;
	private String entryUrl;
	private String text;
	private int likeNumber;
	private int shareNumber;
	private int commentNumber;
	private String sourceDevice;
	private boolean isShared;
	private Integer originLikeNumber;
	private Integer originShareNumber;
	private String originText;
	private Integer originCommentNumber;
	private Date publishedTime;
	private boolean hasRead;
	private String classHolder;

	public WeiboEntry() {
	}

	public WeiboEntry(WeiboUrl weiboUrl, String entryUrl, String text, int likeNumber, int shareNumber,
			int commentNumber, boolean isShared, Date publishedTime, boolean hasRead) {
		this.weiboUrl = weiboUrl;
		this.entryUrl = entryUrl;
		this.text = text;
		this.likeNumber = likeNumber;
		this.shareNumber = shareNumber;
		this.commentNumber = commentNumber;
		this.isShared = isShared;
		this.publishedTime = publishedTime;
		this.hasRead = hasRead;
	}

	public WeiboEntry(WeiboUrl weiboUrl, String entryUrl, String text, int likeNumber, int shareNumber,
			int commentNumber, String sourceDevice, boolean isShared, Integer originLikeNumber,
			Integer originShareNumber, String originText, Integer originCommentNumber, Date publishedTime,
			boolean hasRead, String classHolder) {
		this.weiboUrl = weiboUrl;
		this.entryUrl = entryUrl;
		this.text = text;
		this.likeNumber = likeNumber;
		this.shareNumber = shareNumber;
		this.commentNumber = commentNumber;
		this.sourceDevice = sourceDevice;
		this.isShared = isShared;
		this.originLikeNumber = originLikeNumber;
		this.originShareNumber = originShareNumber;
		this.originText = originText;
		this.originCommentNumber = originCommentNumber;
		this.publishedTime = publishedTime;
		this.hasRead = hasRead;
		this.classHolder = classHolder;
	}

	public Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(Integer entryId) {
		this.entryId = entryId;
	}

	public WeiboUrl getWeiboUrl() {
		return this.weiboUrl;
	}

	public void setWeiboUrl(WeiboUrl weiboUrl) {
		this.weiboUrl = weiboUrl;
	}

	public String getEntryUrl() {
		return this.entryUrl;
	}

	public void setEntryUrl(String entryUrl) {
		this.entryUrl = entryUrl;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public int getLikeNumber() {
		return this.likeNumber;
	}

	public void setLikeNumber(int likeNumber) {
		this.likeNumber = likeNumber;
	}

	public int getShareNumber() {
		return this.shareNumber;
	}

	public void setShareNumber(int shareNumber) {
		this.shareNumber = shareNumber;
	}

	public int getCommentNumber() {
		return this.commentNumber;
	}

	public void setCommentNumber(int commentNumber) {
		this.commentNumber = commentNumber;
	}

	public String getSourceDevice() {
		return this.sourceDevice;
	}

	public void setSourceDevice(String sourceDevice) {
		this.sourceDevice = sourceDevice;
	}

	public boolean isIsShared() {
		return this.isShared;
	}

	public void setIsShared(boolean isShared) {
		this.isShared = isShared;
	}

	public Integer getOriginLikeNumber() {
		return this.originLikeNumber;
	}

	public void setOriginLikeNumber(Integer originLikeNumber) {
		this.originLikeNumber = originLikeNumber;
	}

	public Integer getOriginShareNumber() {
		return this.originShareNumber;
	}

	public void setOriginShareNumber(Integer originShareNumber) {
		this.originShareNumber = originShareNumber;
	}

	public String getOriginText() {
		return this.originText;
	}

	public void setOriginText(String originText) {
		this.originText = originText;
	}

	public Integer getOriginCommentNumber() {
		return this.originCommentNumber;
	}

	public void setOriginCommentNumber(Integer originCommentNumber) {
		this.originCommentNumber = originCommentNumber;
	}

	public Date getPublishedTime() {
		return this.publishedTime;
	}

	public void setPublishedTime(Date publishedTime) {
		this.publishedTime = publishedTime;
	}

	public boolean isHasRead() {
		return this.hasRead;
	}

	public void setHasRead(boolean hasRead) {
		this.hasRead = hasRead;
	}

	public String getClassHolder() {
		return this.classHolder;
	}

	public void setClassHolder(String classHolder) {
		this.classHolder = classHolder;
	}

}
