package hibernateMapping;
// Generated 2016-11-4 15:29:32 by Hibernate Tools 5.2.0.Beta1

/**
 * WeiboEntry generated by hbm2java
 */
public class WeiboEntry implements java.io.Serializable {

	private WeiboEntryId id;
	private WeiboUrl weiboUrl;
	private String contentHolder;
	private boolean hasRead;
	private String classHolder;
	private String weiboEntriescol;

	public WeiboEntry() {
	}

	public WeiboEntry(WeiboEntryId id, WeiboUrl weiboUrl, boolean hasRead) {
		this.id = id;
		this.weiboUrl = weiboUrl;
		this.hasRead = hasRead;
	}

	public WeiboEntry(WeiboEntryId id, WeiboUrl weiboUrl, String contentHolder, boolean hasRead, String classHolder,
			String weiboEntriescol) {
		this.id = id;
		this.weiboUrl = weiboUrl;
		this.contentHolder = contentHolder;
		this.hasRead = hasRead;
		this.classHolder = classHolder;
		this.weiboEntriescol = weiboEntriescol;
	}

	public WeiboEntryId getId() {
		return this.id;
	}

	public void setId(WeiboEntryId id) {
		this.id = id;
	}

	public WeiboUrl getWeiboUrl() {
		return this.weiboUrl;
	}

	public void setWeiboUrl(WeiboUrl weiboUrl) {
		this.weiboUrl = weiboUrl;
	}

	public String getContentHolder() {
		return this.contentHolder;
	}

	public void setContentHolder(String contentHolder) {
		this.contentHolder = contentHolder;
	}

	public boolean isHasRead() {
		return this.hasRead;
	}

	public void setHasRead(boolean hasRead) {
		this.hasRead = hasRead;
	}

	public String getClassHolder() {
		return this.classHolder;
	}

	public void setClassHolder(String classHolder) {
		this.classHolder = classHolder;
	}

	public String getWeiboEntriescol() {
		return this.weiboEntriescol;
	}

	public void setWeiboEntriescol(String weiboEntriescol) {
		this.weiboEntriescol = weiboEntriescol;
	}

}
