package hibernateMapping;
// Generated 2016-11-4 15:29:32 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * WeiboEntryId generated by hbm2java
 */
public class WeiboEntryId implements java.io.Serializable {

	private int entryId;
	private Date publishedTime;

	public WeiboEntryId() {
	}

	public WeiboEntryId(int entryId, Date publishedTime) {
		this.entryId = entryId;
		this.publishedTime = publishedTime;
	}

	public int getEntryId() {
		return this.entryId;
	}

	public void setEntryId(int entryId) {
		this.entryId = entryId;
	}

	public Date getPublishedTime() {
		return this.publishedTime;
	}

	public void setPublishedTime(Date publishedTime) {
		this.publishedTime = publishedTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WeiboEntryId))
			return false;
		WeiboEntryId castOther = (WeiboEntryId) other;

		return (this.getEntryId() == castOther.getEntryId())
				&& ((this.getPublishedTime() == castOther.getPublishedTime())
						|| (this.getPublishedTime() != null && castOther.getPublishedTime() != null
								&& this.getPublishedTime().equals(castOther.getPublishedTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEntryId();
		result = 37 * result + (getPublishedTime() == null ? 0 : this.getPublishedTime().hashCode());
		return result;
	}

}
