package hibernateMapping;
// Generated 2016-11-15 22:22:08 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * WeiboUrl generated by hbm2java
 */
public class WeiboUrl implements java.io.Serializable {

	private Integer weiboId;
	private String weiboUrl;
	private int count;
	private Integer tag;
	private boolean isNew;
	private Set weiboEntries = new HashSet(0);
	private Set friends = new HashSet(0);

	public WeiboUrl() {
	}

	public WeiboUrl(int count, boolean isNew) {
		this.count = count;
		this.isNew = isNew;
	}

	public WeiboUrl(String weiboUrl, int count, Integer tag, boolean isNew, Set weiboEntries, Set friends) {
		this.weiboUrl = weiboUrl;
		this.count = count;
		this.tag = tag;
		this.isNew = isNew;
		this.weiboEntries = weiboEntries;
		this.friends = friends;
	}

	public Integer getWeiboId() {
		return this.weiboId;
	}

	public void setWeiboId(Integer weiboId) {
		this.weiboId = weiboId;
	}

	public String getWeiboUrl() {
		return this.weiboUrl;
	}

	public void setWeiboUrl(String weiboUrl) {
		this.weiboUrl = weiboUrl;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Integer getTag() {
		return this.tag;
	}

	public void setTag(Integer tag) {
		this.tag = tag;
	}

	public boolean isIsNew() {
		return this.isNew;
	}

	public void setIsNew(boolean isNew) {
		this.isNew = isNew;
	}

	public Set getWeiboEntries() {
		return this.weiboEntries;
	}

	public void setWeiboEntries(Set weiboEntries) {
		this.weiboEntries = weiboEntries;
	}

	public Set getFriends() {
		return this.friends;
	}

	public void setFriends(Set friends) {
		this.friends = friends;
	}

}
