package hibernateMapping;
// Generated 2016-11-5 19:39:13 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * WeiboEntry generated by hbm2java
 */
public class WeiboEntry implements java.io.Serializable {

	private Integer entryId;
	private WeiboUrl weiboUrl;
	private String contentHolder;
	private Date publishedTime;
	private boolean hasRead;
	private String classHolder;
	private String weiboEntriescol;

	public WeiboEntry() {
	}

	public WeiboEntry(WeiboUrl weiboUrl, Date publishedTime, boolean hasRead) {
		this.weiboUrl = weiboUrl;
		this.publishedTime = publishedTime;
		this.hasRead = hasRead;
	}

	public WeiboEntry(WeiboUrl weiboUrl, String contentHolder, Date publishedTime, boolean hasRead, String classHolder,
			String weiboEntriescol) {
		this.weiboUrl = weiboUrl;
		this.contentHolder = contentHolder;
		this.publishedTime = publishedTime;
		this.hasRead = hasRead;
		this.classHolder = classHolder;
		this.weiboEntriescol = weiboEntriescol;
	}

	public Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(Integer entryId) {
		this.entryId = entryId;
	}

	public WeiboUrl getWeiboUrl() {
		return this.weiboUrl;
	}

	public void setWeiboUrl(WeiboUrl weiboUrl) {
		this.weiboUrl = weiboUrl;
	}

	public String getContentHolder() {
		return this.contentHolder;
	}

	public void setContentHolder(String contentHolder) {
		this.contentHolder = contentHolder;
	}

	public Date getPublishedTime() {
		return this.publishedTime;
	}

	public void setPublishedTime(Date publishedTime) {
		this.publishedTime = publishedTime;
	}

	public boolean isHasRead() {
		return this.hasRead;
	}

	public void setHasRead(boolean hasRead) {
		this.hasRead = hasRead;
	}

	public String getClassHolder() {
		return this.classHolder;
	}

	public void setClassHolder(String classHolder) {
		this.classHolder = classHolder;
	}

	public String getWeiboEntriescol() {
		return this.weiboEntriescol;
	}

	public void setWeiboEntriescol(String weiboEntriescol) {
		this.weiboEntriescol = weiboEntriescol;
	}

}
