package hibernateMapping;
// Generated 2016-11-7 22:10:10 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * WeiboUrl generated by hbm2java
 */
public class WeiboUrl implements java.io.Serializable {

	private Integer weiboId;
	private String weiboUrl;
	private int count;
	private Set weiboEntries = new HashSet(0);

	public WeiboUrl() {
	}

	public WeiboUrl(int count) {
		this.count = count;
	}

	public WeiboUrl(String weiboUrl, int count, Set weiboEntries) {
		this.weiboUrl = weiboUrl;
		this.count = count;
		this.weiboEntries = weiboEntries;
	}

	public Integer getWeiboId() {
		return this.weiboId;
	}

	public void setWeiboId(Integer weiboId) {
		this.weiboId = weiboId;
	}

	public String getWeiboUrl() {
		return this.weiboUrl;
	}

	public void setWeiboUrl(String weiboUrl) {
		this.weiboUrl = weiboUrl;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Set getWeiboEntries() {
		return this.weiboEntries;
	}

	public void setWeiboEntries(Set weiboEntries) {
		this.weiboEntries = weiboEntries;
	}

}
