package hibernateMapping;
// Generated 2016-11-7 15:03:58 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * ZhihuEntry generated by hbm2java
 */
public class ZhihuEntry implements java.io.Serializable {

	private Integer entryId;
	private ZhihuUrl zhihuUrl;
	private String contentHolder;
	private Date publishedTime;
	private boolean hasRead;
	private String classHolder;

	public ZhihuEntry() {
	}

	public ZhihuEntry(ZhihuUrl zhihuUrl, Date publishedTime, boolean hasRead) {
		this.zhihuUrl = zhihuUrl;
		this.publishedTime = publishedTime;
		this.hasRead = hasRead;
	}

	public ZhihuEntry(ZhihuUrl zhihuUrl, String contentHolder, Date publishedTime, boolean hasRead,
			String classHolder) {
		this.zhihuUrl = zhihuUrl;
		this.contentHolder = contentHolder;
		this.publishedTime = publishedTime;
		this.hasRead = hasRead;
		this.classHolder = classHolder;
	}

	public Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(Integer entryId) {
		this.entryId = entryId;
	}

	public ZhihuUrl getZhihuUrl() {
		return this.zhihuUrl;
	}

	public void setZhihuUrl(ZhihuUrl zhihuUrl) {
		this.zhihuUrl = zhihuUrl;
	}

	public String getContentHolder() {
		return this.contentHolder;
	}

	public void setContentHolder(String contentHolder) {
		this.contentHolder = contentHolder;
	}

	public Date getPublishedTime() {
		return this.publishedTime;
	}

	public void setPublishedTime(Date publishedTime) {
		this.publishedTime = publishedTime;
	}

	public boolean isHasRead() {
		return this.hasRead;
	}

	public void setHasRead(boolean hasRead) {
		this.hasRead = hasRead;
	}

	public String getClassHolder() {
		return this.classHolder;
	}

	public void setClassHolder(String classHolder) {
		this.classHolder = classHolder;
	}

}
