package hibernateMapping;
// Generated 2016-11-6 16:06:31 by Hibernate Tools 5.2.0.Beta1

/**
 * ZhihuUrl generated by hbm2java
 */
public class ZhihuUrl implements java.io.Serializable {

	private Integer zhihuId;
	private String zhihuUrl;
	private int count;

	public ZhihuUrl() {
	}

	public ZhihuUrl(int count) {
		this.count = count;
	}

	public ZhihuUrl(String zhihuUrl, int count) {
		this.zhihuUrl = zhihuUrl;
		this.count = count;
	}

	public Integer getZhihuId() {
		return this.zhihuId;
	}

	public void setZhihuId(Integer zhihuId) {
		this.zhihuId = zhihuId;
	}

	public String getZhihuUrl() {
		return this.zhihuUrl;
	}

	public void setZhihuUrl(String zhihuUrl) {
		this.zhihuUrl = zhihuUrl;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
